### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/LV-to-ITX#25]
@johnbrickmaier @mayabostock 
The branches are a hot mess (probably my fault). I will try to fix and be in touch

**Comment by ciozi137** [comment]
Actually, the branch structure is ok - I think I'm just confused:
<img width="647" alt="Screen Shot 2020-07-11 at 9 12 33 AM" src="https://user-images.githubusercontent.com/26659428/87224853-bdf86d80-c356-11ea-905f-4968e23f4741.png">

Maybe I need to merge aws and commands into develop, and then we should branch from develop into "commands", "aws", "pg" branches for new features:

This is my goal:

<img width="617" alt="Screen Shot 2020-07-11 at 9 37 21 AM" src="https://user-images.githubusercontent.com/26659428/87225336-2137cf00-c35a-11ea-8b90-fd2c7856847b.png">

looping @phil-shenk  in here too

**Comment by phil-shenk** [comment]
aws was just a temporary branch to help merge in the S3 stuff a while back, and can be deleted I think, unless someone has been using it. I've been branching off from 'development' into things like 'development-issue21' then merging back into development to make my changes

**Comment by ciozi137** [comment]
cool thanks for confirming

**Comment by ciozi137** [comment]
I think this is fixed...
